[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "sulaunch"
authors = [{name = "Umut Şahin Önder", email = "umutonder@sabanciuniv.edu"}]
dynamic = ["version", "description"]
